[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
pvp_program = "F2LhVGUa9yLbYVYujYMPyckqWmsokHE9wym7ceGHWUMZ"

[programs.mainnet]
pvp_program = "HWgLWiR6CjdpTstrasbKsfGbrv67sZERai8v5wQaDW39"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/pvp_program"]

[scripts]
migrate = "ts-node migrations/deploy.ts"
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = true
